window.MX_DATA = (() => {
  const IMG = '../../assets/img/';
  const solutions = [
    { id: 'web', n: '01', cat: 'Presencia', title: 'Web corporativa', icon: 'monitor-smartphone', img: IMG + 'servicio-web.jpg', desc: 'Presencia digital profesional orientada a generar confianza y oportunidades.', stat: { v: '< 1.5 s', l: 'carga objetivo' },
      detail: { headline: 'Un sitio que trabaja para tu área comercial.', lead: 'Diseñamos sitios corporativos que explican con claridad qué haces, a quién sirves y por qué elegirte — y que convierten visitas en conversaciones.', bullets: ['arquitectura de contenido', 'diseño a la medida', 'formularios conectados al CRM', 'SEO técnico', 'multi-idioma', 'panel para editar contenido', 'analítica configurada'], ideal: 'Empresas cuya web actual no refleja su tamaño real, no genera contactos o no se puede actualizar sin depender de alguien.', build: ['sitio corporativo', 'landing de campaña', 'portal de marca', 'micrositio de producto', 'sección de vacantes', 'blog corporativo'] } },
    { id: 'ecommerce', n: '02', cat: 'Venta', title: 'E-commerce', icon: 'shopping-bag', img: IMG + 'servicio-ecommerce.jpg', desc: 'Tiendas online diseñadas para vender y escalar.', stat: { v: 'B2B · B2C', l: 'catálogos y mayoreo' },
      detail: { headline: 'Vende en línea con la operación resuelta.', lead: 'Tiendas conectadas a tu inventario, logística y facturación, pensadas para vender a consumidores, distribuidores o ambos.', bullets: ['catálogo e inventario', 'precios por cliente', 'pagos y facturación CFDI', 'envíos y guías', 'carritos recuperables', 'reportes de venta'], ideal: 'Marcas y distribuidoras que quieren vender directo, abrir un canal mayorista o dejar de tomar pedidos por WhatsApp.', build: ['tienda en línea', 'portal de pedidos B2B', 'catálogo mayorista', 'integración con ERP', 'marketplace interno', 'programa de lealtad'] } },
    { id: 'sistemas', n: '03', cat: 'Operación', title: 'Sistemas empresariales', icon: 'layout-dashboard', img: IMG + 'servicio-sistemas.jpg', desc: 'Software interno adaptado a la operación real de cada empresa.', stat: { v: '7 módulos', l: 'base configurable' },
      detail: { headline: 'Software diseñado alrededor de tu operación.', lead: 'Construimos herramientas internas para gestionar lo que hoy vive en hojas de cálculo, correos y sistemas que no se hablan entre sí.', bullets: ['clientes', 'órdenes', 'inventario', 'usuarios', 'procesos', 'reportes', 'métricas'], ideal: 'Empresas que ya dependen de procesos manuales o múltiples herramientas desconectadas.', build: ['panel administrativo', 'sistema interno', 'CRM', 'ERP personalizado', 'dashboard', 'portal de clientes'] } },
    { id: 'automatizacion', n: '04', cat: 'Eficiencia', title: 'Automatización', icon: 'workflow', img: IMG + 'servicio-automatizacion.jpg', desc: 'Eliminación de tareas repetitivas y optimización de procesos.', stat: { v: '−60%', l: 'captura manual*' },
      detail: { headline: 'Que el trabajo repetitivo se haga solo.', lead: 'Identificamos las tareas que tu equipo repite todos los días y las convertimos en flujos automáticos, medibles y con responsables claros.', bullets: ['captura de leads', 'asignación automática', 'notificaciones', 'generación de documentos', 'conciliaciones', 'recordatorios de seguimiento'], ideal: 'Equipos que copian datos entre sistemas, persiguen aprobaciones por correo o pierden seguimiento de clientes.', build: ['flujos de aprobación', 'bots de notificación', 'sincronización de datos', 'reportes automáticos', 'onboarding de clientes', 'alertas operativas'] } },
    { id: 'marketing', n: '05', cat: 'Captación', title: 'Marketing & SEO', icon: 'chart-no-axes-combined', img: IMG + 'servicio-marketing.jpg', desc: 'Captación de tráfico, clientes y crecimiento digital.', stat: { v: 'Mensual', l: 'reporte de resultados' },
      detail: { headline: 'Tráfico que se convierte en clientes.', lead: 'Estrategia de posicionamiento, contenido y campañas medidas contra oportunidades reales de negocio, no solo contra clics.', bullets: ['SEO técnico y de contenido', 'campañas de pago', 'landing pages', 'medición de conversiones', 'contenido para decisores', 'reportes mensuales'], ideal: 'Empresas con buen producto pero poca visibilidad, o que invierten en anuncios sin saber qué funciona.', build: ['estrategia SEO', 'campañas Google / Meta / LinkedIn', 'embudos de captación', 'tablero de marketing', 'contenido técnico', 'automatización de correo'] } },
    { id: 'integraciones', n: '06', cat: 'Conexión', title: 'Integraciones', icon: 'plug-zap', desc: 'Conectamos herramientas, sistemas y procesos.', stat: { v: 'API · ERP · CRM', l: 'conectores' }, chips: ['ERP', 'CRM', 'Facturación', 'Pagos', 'Paquetería', 'WhatsApp'],
      detail: { headline: 'Tus herramientas, hablando entre sí.', lead: 'Conectamos los sistemas que ya usas para que la información fluya sin capturas dobles ni archivos intermedios.', bullets: ['APIs a la medida', 'ERP y contabilidad', 'pasarelas de pago', 'facturación electrónica', 'paqueterías', 'mensajería'], ideal: 'Operaciones donde la misma información se captura dos o tres veces en sistemas distintos.', build: ['middleware de integración', 'sincronización ERP ↔ tienda', 'webhooks', 'conectores de facturación', 'APIs para socios', 'migración de datos'] } },
    { id: 'crm', n: '07', cat: 'Comercial', title: 'CRM & clientes', icon: 'contact', desc: 'Centralización y gestión de oportunidades comerciales.', stat: { v: 'Pipeline', l: 'por etapa y vendedor' }, pipeline: [['Nuevo', 38], ['Contactado', 26], ['Propuesta', 14], ['Cierre', 7]],
      detail: { headline: 'Cada oportunidad, con dueño y siguiente paso.', lead: 'Implementamos o construimos el CRM que se adapta a cómo vende tu equipo, conectado a tus canales de entrada.', bullets: ['pipeline por etapas', 'historial de cliente', 'tareas y recordatorios', 'cotizaciones', 'metas por vendedor', 'reportes comerciales'], ideal: 'Equipos comerciales que gestionan clientes en Excel, WhatsApp personal o la memoria del vendedor.', build: ['CRM a la medida', 'implementación de CRM', 'portal de distribuidores', 'cotizador', 'tablero comercial', 'app para vendedores'] } },
    { id: 'analitica', n: '08', cat: 'Decisión', title: 'Analítica', icon: 'chart-line', desc: 'Dashboards para entender qué está pasando en el negocio.', stat: { v: 'Tiempo real', l: 'indicadores clave' }, spark: [12, 18, 14, 22, 19, 28, 26, 34, 31, 40, 38, 46],
      detail: { headline: 'Decide con datos del día, no del mes pasado.', lead: 'Reunimos la información de ventas, operación y marketing en tableros claros para cada nivel de la empresa.', bullets: ['indicadores por área', 'tableros directivos', 'alertas', 'reportes automáticos', 'modelado de datos', 'acceso por rol'], ideal: 'Direcciones que esperan días por un reporte o reciben números distintos de cada área.', build: ['dashboard directivo', 'tablero de ventas', 'reportes operativos', 'data warehouse ligero', 'KPIs financieros', 'alertas de negocio'] } }
  ];
  const problems = [
    { id: 'clientes', icon: 'users', label: 'Tengo pocos clientes', problem: 'Nuestro producto es bueno, pero no llegan suficientes prospectos calificados.', solution: ['Marketing & SEO', 'Web corporativa', 'CRM & clientes'], solIds: ['marketing', 'web', 'crm'], result: 'Un canal de captación medible, con cada prospecto registrado y con seguimiento.', kpi: { v: '+180%', l: 'oportunidades (ejemplo)' } },
    { id: 'manual', icon: 'timer', label: 'Mi empresa pierde tiempo en procesos manuales', problem: 'Perdemos mucho tiempo haciendo tareas manuales.', solution: ['Automatización', 'Integraciones', 'Sistema interno'], solIds: ['automatizacion', 'integraciones', 'sistemas'], result: 'Menos trabajo repetitivo y procesos más rápidos.', kpi: { v: '+12 h', l: 'semanales recuperadas (ejemplo)' } },
    { id: 'online', icon: 'shopping-cart', label: 'Necesito vender online', problem: 'Nuestros clientes quieren comprar en línea y hoy solo vendemos por teléfono o en sucursal.', solution: ['E-commerce', 'Integraciones', 'Analítica'], solIds: ['ecommerce', 'integraciones', 'analitica'], result: 'Un canal de venta abierto 24/7 conectado a inventario y facturación.', kpi: { v: '24/7', l: 'canal de venta activo' } },
    { id: 'desorden', icon: 'shuffle', label: 'Mi operación está desorganizada', problem: 'Cada área trabaja con su propia hoja de cálculo y nadie tiene la información completa.', solution: ['Sistema empresarial', 'Analítica', 'Automatización'], solIds: ['sistemas', 'analitica', 'automatizacion'], result: 'Una sola fuente de información, responsables claros y visibilidad para dirección.', kpi: { v: '1', l: 'fuente única de datos' } },
    { id: 'digitalizar', icon: 'scan-line', label: 'Necesito digitalizar mi empresa', problem: 'Seguimos dependiendo de papel, correos y archivos sueltos para operar.', solution: ['Diagnóstico', 'Sistema interno', 'Automatización'], solIds: ['sistemas', 'automatizacion', 'integraciones'], result: 'Procesos digitales por etapas, sin detener la operación actual.', kpi: { v: 'Por fases', l: 'sin frenar la operación' } },
    { id: 'sistema', icon: 'server-cog', label: 'Necesito un sistema interno', problem: 'Ningún software comercial se adapta a cómo trabajamos realmente.', solution: ['Sistema empresarial', 'Integraciones', 'Portal de clientes'], solIds: ['sistemas', 'integraciones', 'crm'], result: 'Software propio, alineado a tus procesos y que crece con la empresa.', kpi: { v: '100%', l: 'adaptado a tu proceso' } },
    { id: 'web', icon: 'globe', label: 'Ya tengo página pero no funciona', problem: 'Tenemos sitio web, pero no genera contactos ni representa a la empresa.', solution: ['Rediseño web', 'SEO técnico', 'Analítica'], solIds: ['web', 'marketing', 'analitica'], result: 'Un sitio que se encuentra, se entiende y genera solicitudes medibles.', kpi: { v: '×3', l: 'solicitudes (ejemplo)' } },
    { id: 'automatizar', icon: 'bot', label: 'Quiero automatizar', problem: 'Sabemos que muchas tareas podrían hacerse solas, pero no sabemos por dónde empezar.', solution: ['Mapa de procesos', 'Automatización', 'Integraciones'], solIds: ['automatizacion', 'integraciones', 'crm'], result: 'Un plan priorizado por impacto y los primeros flujos funcionando en semanas.', kpi: { v: '4–6 sem', l: 'primeros flujos activos' } }
  ];
  const flow = [
    { id: 'cliente', icon: 'user-round', label: 'Cliente', t: '00:00', tip: 'Un prospecto llega desde Google, redes o una recomendación.' },
    { id: 'form', icon: 'file-input', label: 'Formulario', t: '00:01', tip: 'Llena un formulario corto; los datos se validan al instante.' },
    { id: 'crm', icon: 'database', label: 'CRM', t: '00:01', tip: 'Se crea el contacto y la oportunidad sin captura manual.' },
    { id: 'notif', icon: 'bell-ring', label: 'Notificación', t: '00:02', tip: 'El equipo comercial recibe aviso por correo y WhatsApp.' },
    { id: 'asig', icon: 'user-check', label: 'Asignación', t: '00:02', tip: 'Se asigna al vendedor según zona, industria o carga de trabajo.' },
    { id: 'seg', icon: 'calendar-clock', label: 'Seguimiento', t: '24 h', tip: 'Recordatorios automáticos si no hay contacto en 24 horas.' },
    { id: 'venta', icon: 'badge-check', label: 'Venta', t: 'Cierre', tip: 'La venta se registra y dispara facturación y onboarding.' }
  ];
  const modules = [['users', 'Clientes'], ['receipt', 'Ventas'], ['package', 'Órdenes'], ['boxes', 'Inventario'], ['landmark', 'Finanzas'], ['shield-check', 'Usuarios'], ['file-bar-chart', 'Reportes']];
  const systemTabs = {
    resumen: { kpis: [['Ingresos del mes', '$2.84 M', '+8.2%'], ['Órdenes activas', '312', '+14'], ['Cumplimiento', '96.4%', '+1.1 pt']], bars: [42, 48, 45, 52, 58, 55, 62, 60, 68, 72, 70, 78], rows: [['OR-10482', 'Constructora Sierra Alta', 'En ruta', '$84,200'], ['OR-10481', 'Ferremax del Bajío', 'Preparando', '$23,950'], ['OR-10479', 'Grupo Vértice', 'Entregado', '$112,400'], ['OR-10477', 'Comercial Tapatía', 'Facturado', '$41,780']] },
    ventas: { kpis: [['Ventas netas', '$1.92 M', '+11.6%'], ['Ticket promedio', '$18,430', '+4.3%'], ['Cotizaciones', '148', '+22']], bars: [30, 38, 35, 44, 50, 47, 58, 64, 61, 70, 76, 82], rows: [['CT-2291', 'Hoteles Maren', 'Propuesta', '$236,000'], ['CT-2290', 'Clínica Valle Norte', 'Negociación', '$98,500'], ['CT-2288', 'Agroindustrias Río Verde', 'Ganada', '$154,300'], ['CT-2285', 'Logística Pacífico', 'Enviada', '$67,900']] },
    clientes: { kpis: [['Clientes activos', '1,286', '+38'], ['Retención 12m', '91.2%', '+2.4 pt'], ['NPS', '64', '+5']], bars: [60, 62, 61, 65, 66, 68, 70, 71, 74, 75, 77, 80], rows: [['CL-0932', 'Grupo Vértice', 'Premium', '$1.2 M'], ['CL-0918', 'Ferremax del Bajío', 'Recurrente', '$640 K'], ['CL-0907', 'Hoteles Maren', 'Nuevo', '$236 K'], ['CL-0899', 'Comercial Tapatía', 'Recurrente', '$410 K']] },
    operaciones: { kpis: [['Tiempo de surtido', '3.2 h', '−0.8 h'], ['Inventario disponible', '94%', '+3 pt'], ['Incidencias', '7', '−5']], bars: [70, 64, 66, 58, 55, 52, 49, 46, 44, 41, 38, 35], rows: [['AL-01', 'Almacén Monterrey', 'Óptimo', '98%'], ['AL-02', 'Almacén CDMX', 'Óptimo', '95%'], ['AL-03', 'Almacén Guadalajara', 'Revisar', '82%'], ['AL-04', 'Cross-dock Querétaro', 'Óptimo', '97%']] }
  };
  const seeded = (seed) => () => (seed = (seed * 9301 + 49297) % 233280) / 233280;
  const series = (n, base, growth, noise, seed) => { const r = seeded(seed); return Array.from({ length: n }, (_, i) => Math.round(base * (1 + growth * i / n) * (1 + (r() - .5) * noise))); };
  const analytics = {
    '7d': { kpis: { visitas: 11842, conv: 29.4, leads: 318, ventas: 104300 }, traffic: series(7, 1500, .25, .18, 3), leadsS: series(7, 40, .3, .3, 5) },
    '30d': { kpis: { visitas: 48291, conv: 32.8, leads: 1284, ventas: 428900 }, traffic: series(30, 1350, .45, .22, 7), leadsS: series(30, 34, .55, .35, 11) },
    '90d': { kpis: { visitas: 131560, conv: 27.1, leads: 3412, ventas: 1186400 }, traffic: series(45, 1100, .7, .2, 13), leadsS: series(45, 26, .8, .3, 17) }
  };
  const sources = [['Orgánico (SEO)', 41], ['Campañas de pago', 24], ['Directo', 16], ['Referidos', 11], ['Redes sociales', 8]];
  const process = [
    { n: '01', icon: 'search', title: 'Entendemos', text: 'Analizamos el negocio, operación, objetivos y problemas.', out: 'Diagnóstico y mapa de procesos' },
    { n: '02', icon: 'pen-tool', title: 'Diseñamos', text: 'Definimos la solución, arquitectura y experiencia.', out: 'Propuesta, alcance y prototipo' },
    { n: '03', icon: 'code-xml', title: 'Desarrollamos', text: 'Construimos, integramos y probamos.', out: 'Entregas quincenales y pruebas' },
    { n: '04', icon: 'rocket', title: 'Evolucionamos', text: 'Lanzamos, medimos y seguimos mejorando.', out: 'Soporte, métricas y mejoras' }
  ];
  const cases = [
    { id: 'constructa', name: 'Constructa', industry: 'Construcción', city: 'Monterrey, N.L.', img: IMG + 'caso-constructa.jpg', solutionShort: 'Sitio corporativo + estrategia digital', problem: 'Necesitaba una presencia digital profesional para generar confianza y oportunidades.', result: 'Mayor presencia digital y generación de oportunidades.',
      reto: 'Constructa competía por proyectos de más de $20 M con un sitio de 2014 que no mostraba su portafolio ni sus certificaciones. Los directores de compras que la investigaban no encontraban razones para incluirla en licitaciones.', solucion: 'Replanteamos su posicionamiento para desarrolladores e industria, construimos un sitio corporativo con portafolio filtrable por tipo de obra y conectamos cada solicitud a su CRM comercial.', built: ['Sitio corporativo bilingüe', 'Portafolio de obras con filtros', 'Formulario de licitaciones conectado al CRM', 'Estrategia SEO local e industrial', 'Tablero de oportunidades'], metrics: [['+3.4×', 'solicitudes de cotización'], ['62%', 'tráfico orgánico'], ['8 sem', 'de proyecto']], tech: ['Next.js', 'Headless CMS', 'HubSpot', 'Google Analytics 4'] },
    { id: 'orion', name: 'Distribuidora Orión', industry: 'Retail', city: 'Guadalajara, Jal.', img: IMG + 'caso-orion.jpg', solutionShort: 'E-commerce + experiencia de compra', problem: 'Vendía únicamente por mostrador y WhatsApp, sin visibilidad de inventario en línea.', result: 'Un canal digital que hoy representa una parte relevante de sus ventas.',
      reto: 'Orión tomaba pedidos de mayoristas por WhatsApp y los capturaba a mano en su ERP. Los errores de inventario generaban cancelaciones y los clientes minoristas no tenían forma de comprar en línea.', solucion: 'Diseñamos una tienda con dos experiencias — consumidor final y mayoreo con precios por cliente — sincronizada en tiempo real con su inventario y facturación.', built: ['Tienda en línea B2C', 'Portal de pedidos mayoristas', 'Sincronización con ERP', 'Facturación CFDI automática', 'Integración con paqueterías'], metrics: [['+230%', 'ventas en línea'], ['−70%', 'captura manual'], ['4.8/5', 'satisfacción de compra']], tech: ['Shopify Plus', 'Node.js', 'API ERP', 'Stripe', 'Skydropx'] },
    { id: 'lumen', name: 'Grupo Lumen', industry: 'Servicios', city: 'Ciudad de México', img: IMG + 'caso-lumen.jpg', solutionShort: 'Automatización + procesos internos', problem: 'Coordinaba 40 personas en campo con hojas de cálculo y correos.', result: 'Procesos internos automatizados y más de 15 horas semanales recuperadas.',
      reto: 'Grupo Lumen coordinaba servicios de mantenimiento con hojas de cálculo compartidas. Asignar, confirmar y facturar cada servicio requería cinco pasos manuales y muchas llamadas.', solucion: 'Mapeamos el proceso completo, eliminamos pasos duplicados y construimos un sistema interno con asignación automática, app para técnicos y reportes para dirección.', built: ['Sistema de órdenes de servicio', 'App para técnicos en campo', 'Asignación automática por zona', 'Notificaciones a clientes', 'Dashboard directivo'], metrics: [['+15 h', 'semanales recuperadas'], ['−45%', 'tiempo de asignación'], ['100%', 'servicios trazables']], tech: ['React', 'PostgreSQL', 'n8n', 'WhatsApp Business API', 'Metabase'] }
  ];
  const stages = [
    { id: 'inicio', icon: 'sprout', title: 'Estoy empezando', text: 'Necesito construir mi presencia digital.', rec: ['web', 'marketing', 'crm'], note: 'Empieza con una base sólida: un sitio que genere confianza, medición desde el primer día y un lugar donde registrar a cada prospecto.' },
    { id: 'clientes', icon: 'handshake', title: 'Ya tengo clientes', text: 'Necesito crecer y profesionalizar mi operación.', rec: ['crm', 'ecommerce', 'marketing'], note: 'Ordena tu proceso comercial y abre nuevos canales de venta sin sumar trabajo manual.' },
    { id: 'creciendo', icon: 'trending-up', title: 'Estoy creciendo', text: 'Necesito sistemas y automatización.', rec: ['automatizacion', 'sistemas', 'integraciones'], note: 'Cuando el volumen crece, los procesos manuales se vuelven el cuello de botella. Es momento de automatizar y conectar.' },
    { id: 'grande', icon: 'building-2', title: 'Mi empresa ya es grande', text: 'Necesito tecnología adaptada a procesos complejos.', rec: ['sistemas', 'integraciones', 'analitica'], note: 'Software a la medida, integraciones con tus sistemas actuales y visibilidad directiva sobre toda la operación.' }
  ];
  const goals = [['clientes', 'Conseguir más clientes', 'users'], ['online', 'Vender online', 'shopping-cart'], ['automatizar', 'Automatizar procesos', 'workflow'], ['digitalizar', 'Digitalizar mi empresa', 'scan-line'], ['sistema', 'Crear un sistema', 'server-cog'], ['web', 'Mejorar mi página', 'globe'], ['integrar', 'Integrar herramientas', 'plug-zap'], ['nose', 'No estoy seguro', 'circle-help']];
  const goalRec = { clientes: ['marketing', 'web', 'crm'], online: ['ecommerce', 'integraciones', 'marketing'], automatizar: ['automatizacion', 'integraciones', 'sistemas'], digitalizar: ['sistemas', 'automatizacion', 'analitica'], sistema: ['sistemas', 'integraciones', 'analitica'], web: ['web', 'marketing', 'analitica'], integrar: ['integraciones', 'automatizacion', 'analitica'], nose: ['web', 'automatizacion', 'analitica'] };
  const sizes = ['1–5 personas', '6–20', '21–50', '51–100', '100+'];
  const timing = [['explorando', 'Estoy explorando'], ['pronto', 'Próximamente'], ['mes', 'Este mes'], ['ya', 'Lo necesitamos cuanto antes']];
  const trust = ['Grupo Lumen', 'Novatec', 'Constructa', 'Distribuidora Orión', 'Alpha', 'Rivera'];
  return { solutions, problems, flow, modules, systemTabs, analytics, sources, process, cases, stages, goals, goalRec, sizes, timing, trust, IMG };
})();
